### ISSUE TITLE
Not an issue but for future refence

### ISSUE THREAD

**Issue by ImpulsiveLass** [Azim/LethalPresents#2] opened 2023-12-19 20:05 UTC
What do you call the entities in the blocklist?
like hoarding_bug, bracken, coil-head, thumper 
?
I looked it up and couldn't find the names in code so I'm asking what you are supposed to type to specify the entities

**Comment by Azim** [comment] 2023-12-19 20:18
I am comparing the entity type name against the in-game list, so that even modded entities should work fine (in theory).

Currently i am dumping a list of all possible spawnable entities into bepinex logs upon level load (keep in mind this list can change between levels), for example this is the list you get on rainy experimentation:
![image](https://github.com/Azim/LethalPresents/assets/16478424/0bc54947-8086-48ab-850f-19e2cf10043e)

**Comment by Azim** [comment] 2023-12-19 20:20
If you are using r2modman, you can find this log at `%AppData%\r2modmanPlus-local\LethalCompany\profiles\<YourCurrentProfile>\BepInEx\LogOutput.log`

**Comment by ImpulsiveLass** [comment] 2023-12-19 20:34
Oh side note, why does it need an indoor AND an outdoor? Why can't it just be hoarding bug?

**Comment by Azim** [comment] 2023-12-19 20:50
Some of the indoor enemies dont have the logic to work properly when outside, and i think same applies to the outside enemies working inside.
For example, coilhead straight up doesnt see you outside and causes the game to lag a lot

**Comment by ImpulsiveLass** [comment] 2023-12-19 20:55
so you made it so the hoarding bug CAN'T spawn outside?

**Comment by ImpulsiveLass** [comment] 2023-12-19 20:58
![Screenshot 2023-12-19 155814](https://github.com/Azim/LethalPresents/assets/92990441/e6042df2-8200-42ba-9d73-78051c8807b0)
Why doesn't this work?

**Comment by Azim** [comment] 2023-12-20 05:32
> so you made it so the hoarding bug CAN'T spawn outside?

yes, unless other mods make it so that hoarding bug can naturally spawn outside, it will only spawn inside.


> ![Screenshot 2023-12-19 155814](https://private-user-images.githubusercontent.com/92990441/291712217-e6042df2-8200-42ba-9d73-78051c8807b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTA0NzAsIm5iZiI6MTcwMzA1MDE3MCwicGF0aCI6Ii85Mjk5MDQ0MS8yOTE3MTIyMTctZTYwNDJkZjItODIwMC00MmJhLTlkNzMtNzgwNTFjODgwN2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA1MjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMjhiNDlhM2I4ZTAyMmUwNTI1MGY5OTg1M2JjZTlmN2VjNjhkNTc5ODVmOGUyMjNiNTM4NDMzNjU0ZDdjNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eBhiSDC-rTz4Yuh-DKr7ZggT6XjRaV_xNZGJBrUcrWo) Why doesn't this work?

This should prevent dogs and hoarding bugs from spawning out of the present (obviously im not touching the regular enemy spawns)

**Comment by ImpulsiveLass** [comment] 2024-01-05 17:32
I still can't get this mod to do anything, I create a whitelist and it just spawns scrap even when the game is at 99% spawn chance

**Comment by Azim** [comment] 2024-01-05 17:34
Send your config so i can try and reproduce?

**Comment by ImpulsiveLass** [comment] 2024-01-05 17:35
## Settings file was created by plugin LethalPresents v1.0.3
## Plugin GUID: LethalPresents

[General]

## Chance of spawning an enemy when opening a present [0-100]
# Setting type: Int32
# Default value: 5
SpawnChance = 99

## Enemy blocklist separated by , and without whitespaces
# Setting type: String
# Default value: 
EnemyBlocklist = MouthDog,HoarderBug

## Turns blocklist into allowlist, blocklist must contain at least one inside and one outside enemy, use at your own risk
# Setting type: Boolean
# Default value: false
IsAllowlist = true

## Add mines to the spawn pool [WIP]
# Setting type: Boolean
# Default value: true
ShouldSpawnMines = false

## Add turrets to the spawn pool [WIP]
# Setting type: Boolean
# Default value: true
ShouldSpawnTurrets = false

**Comment by ImpulsiveLass** [comment] 2024-01-05 17:45
Something else to note is does the mod add enemies to spawn on all planets or does it obey the natural spawns for whatever reason? Because if it does that can very easily break the mod if something on the list is just not natural on a planet like having giant on the list at experimentation

**Comment by ImpulsiveLass** [comment] 2024-01-05 18:06
![Screenshot 2024-01-05 130610](https://github.com/Azim/LethalPresents/assets/92990441/ce479e67-2b90-4e0b-a344-7fe51c233e0c)
ok I pulled this list of names from ingame, maybe these work?

**Comment by Azim** [comment] 2024-01-05 18:14
Currently i pull names from `currentLevel` enemies, but tbf most enemies are present on most maps anyway

**Comment by Azim** [comment] 2024-01-05 18:14
I found the issue with the blacklist/whitelist though, thanks, gonna be fixed in next update

**Comment by ImpulsiveLass** [comment] 2024-01-05 18:25
the boolean is broke?

**Comment by ImpulsiveLass** [comment] 2024-01-05 18:27
Or are you going to switch the mod to use the complete list?

**Comment by ImpulsiveLass** [comment] 2024-01-05 18:37
> > so you made it so the hoarding bug CAN'T spawn outside?
> 
> yes, unless other mods make it so that hoarding bug can naturally spawn outside, it will only spawn inside.
> 
> > ![Screenshot 2023-12-19 155814](https://private-user-images.githubusercontent.com/92990441/291712217-e6042df2-8200-42ba-9d73-78051c8807b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTA0NzAsIm5iZiI6MTcwMzA1MDE3MCwicGF0aCI6Ii85Mjk5MDQ0MS8yOTE3MTIyMTctZTYwNDJkZjItODIwMC00MmJhLTlkNzMtNzgwNTFjODgwN2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA1MjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMjhiNDlhM2I4ZTAyMmUwNTI1MGY5OTg1M2JjZTlmN2VjNjhkNTc5ODVmOGUyMjNiNTM4NDMzNjU0ZDdjNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eBhiSDC-rTz4Yuh-DKr7ZggT6XjRaV_xNZGJBrUcrWo) Why doesn't this work?
> 
> This should prevent dogs and hoarding bugs from spawning out of the present (obviously im not touching the regular enemy spawns)

Oh huh there is a fork that should allow for universal spawn locations but I'm not sure if its an addition or its own mod, its not on thunderstore https://github.com/Aristotelis2002/LethalPresentsExperimental
It would be very cool if it could be made  basekit 🥺

**Comment by Azim** [comment] 2024-01-05 19:19
> the boolean is broke?

the name check itself was broken

**Comment by Azim** [comment] 2024-01-05 19:22
> Or are you going to switch the mod to use the complete list?

I am not allowing inside enemies to spawn outside because it is very buggy even with Lethal Escape mod.

I tried and it was causing desyncs and all sorts of issues, ultimately not worth implementing it.

Same for *all* enemies vs *naturally spawning* enemies - if it doesnt spawn naturally, its very likely that spawning it would cause issues

**Comment by ImpulsiveLass** [comment] 2024-01-05 20:00
Trying to see if I can get it to work with lethal escape so that hoarding bugs can come out of the box on the surface but something is preventing that despite the code being adapted to the the surface

**Comment by ImpulsiveLass** [comment] 2024-01-05 20:04
by default it makes sense for them to be seperate but could you either add a boolean (stated that it can really break the game if enabled) to enable the Univeral spawning or have the mod enable it when it is loaded alongside lethalescape? I think it would be really funny for my friend to open a box on the ship and have it spawn a hoarding bug who makes the ship its nest until we BEAT IT

**Comment by Azim** [comment] 2024-01-06 07:11
> by default it makes sense for them to be seperate but could you either add a boolean (stated that it can really break the game if enabled) to enable the Univeral spawning or have the mod enable it when it is loaded alongside lethalescape? I think it would be really funny for my friend to open a box on the ship and have it spawn a hoarding bug who makes the ship its nest until we BEAT IT

alright

**Comment by apeng0907** [comment] 2024-03-15 08:12
May I ask what is the list of all supported organisms now? Is it separated by a space or a comma in the middle?

**Comment by apeng0907** [comment] 2024-03-15 08:12
## Settings file was created by plugin LethalPresents v1.0.4
## Plugin GUID: LethalPresents

[General]

## Chance of spawning an enemy when opening a present [0-100]
# Setting type: Int32
# Default value: 5
SpawnChance = 100

## Enemy blocklist separated by , and without whitespaces
# Setting type: String
# Default value: 
EnemyBlocklist = Centipede HoarderBug Thumper Crawler SandSpider Flowerman Nutcracker Masked

## Turns blocklist into allowlist, blocklist must contain at least one inside and one outside enemy, use at your own risk
# Setting type: Boolean
# Default value: false
IsAllowlist = true

## Add mines to the spawn pool
# Setting type: Boolean
# Default value: true
ShouldSpawnMines = false

## Add turrets to the spawn pool
# Setting type: Boolean
# Default value: true
ShouldSpawnTurrets = false

**Comment by Azim** [comment] 2024-03-15 09:35
> May I ask what is the list of all supported organisms now? 

it is shown in game logs

> Is it separated by a space or a comma in the middle?

option description says that its separated by `,`

**Closed as completed** 2024-03-15 09:36 UTC
Labels: question
